# Generated by Django 4.2.4 on 2023-08-20 18:53

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_afp', models.CharField(max_length=45, verbose_name='Nombre de AFP')),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
                'db_table': 'afp',
                'ordering': ['nombre_afp'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=45, verbose_name='Nombre de Banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banco',
                'ordering': ['nombre_banco'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_trabajador', models.CharField(blank=True, max_length=45, verbose_name='Relación del Trabajador')),
                ('documento_descuento', models.CharField(blank=True, max_length=45, verbose_name='Documento de Descuento')),
                ('numero_cuenta', models.CharField(blank=True, max_length=11, verbose_name='Número de Cuenta')),
                ('tipo_descuento', models.CharField(choices=[('MF', 'Monto Fijo'), ('DP', 'Descuento Porcentual')], default='MF', max_length=2, verbose_name='Tipo de Descuento')),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Descuento Fijo')),
                ('porcentaje_descuento', models.IntegerField(blank=True, null=True, verbose_name='Porcentaje de Descuento')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.banco', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=45, verbose_name='Nombre de Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nombre_cargo'],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_descuento', models.CharField(blank=True, help_text='Código de Descuento', max_length=4, null=True, unique=True, verbose_name='Código de Descuento')),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(blank=True, choices=[('DEDUCCION', 'Deducción'), ('APORTE', 'Aporte'), ('OTRO', 'Otro')], default='DEDUCCION', max_length=20, null=True, verbose_name='Tipo de Descuento')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'db_table': 'descuento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(choices=[('HAB', 'Habilitado'), ('LSG', 'Licencia sin goce'), ('LCG', 'Licencia con goce'), ('DES', 'Desabilitado'), ('VAC', 'Vacaciones')], default='HAB', max_length=20, null=True, verbose_name='Situación')),
                ('dias_licencia', models.IntegerField(blank=True, default=0, null=True, verbose_name='Días de Licencia')),
                ('fecha_ini_licencia', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Licencia')),
                ('tiempo_servicios', models.CharField(blank=True, max_length=6, verbose_name='Tiempo de Servicios')),
                ('dias_laborados', models.IntegerField(blank=True, default=30, null=True, verbose_name='Días Laborados')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de Cese')),
                ('documento_contrato', models.CharField(blank=True, max_length=45, verbose_name='Documento de Contrato')),
                ('documento_cese', models.CharField(blank=True, max_length=45, verbose_name='Documento de Cese')),
                ('cuspp', models.CharField(blank=True, max_length=12, verbose_name='CUSPP')),
                ('fecha_afiliacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Afiliación')),
                ('fecha_devengue', models.DateField(blank=True, null=True, verbose_name='Fecha de Devengue')),
                ('codigo_nexus', models.CharField(blank=True, max_length=10, verbose_name='Código Nexus')),
                ('jornada_laboral', models.IntegerField(blank=True, null=True, verbose_name='Jornada Laboral')),
                ('descuentos_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuentos en Días')),
                ('descuentos_horas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuentos en Horas')),
                ('descuentos_minutos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuentos en Minutos')),
                ('leyenda_permanente', models.CharField(blank=True, max_length=45, verbose_name='Leyenda Permanente')),
                ('leyenda_mensual', models.CharField(blank=True, max_length=45, verbose_name='Leyenda Mensual')),
                ('numero_cuenta', models.CharField(blank=True, max_length=45, verbose_name='Número de Cuenta')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.afp', verbose_name='AFP')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.banco', verbose_name='Banco')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='employees.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_haber', models.CharField(blank=True, help_text='Código de Haber', max_length=4, null=True, unique=True, verbose_name='Código de Haber')),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(blank=True, choices=[('SUELDO', 'Sueldo'), ('BONIFICACION', 'Bonificación'), ('DEDUCCION', 'Deducción'), ('BENEFICIOS_SOCIALES', 'Beneficios Sociales')], default='SUELDO', max_length=20, null=True, verbose_name='Tipo de Haber')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberes',
                'db_table': 'haber',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=2, verbose_name='Mes')),
                ('anio', models.CharField(blank=True, max_length=4, verbose_name='Año')),
                ('periodo', models.CharField(blank=True, editable=False, max_length=6, verbose_name='Periodo')),
                ('es_adicional', models.BooleanField(default=False, verbose_name='¿Es adicional?')),
                ('periodo_actual', models.CharField(blank=True, default=None, editable=False, max_length=6, null=True, verbose_name='Periodo Actual')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'db_table': 'periodo',
                'ordering': ['anio', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='RegimenLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regimen_laboral', models.CharField(max_length=45, verbose_name='Nombre de Régimen Laboral')),
            ],
            options={
                'verbose_name': 'Régimen Laboral',
                'verbose_name_plural': 'Regímenes Laborales',
                'db_table': 'regimen_laboral',
                'ordering': ['nombre_regimen_laboral'],
            },
        ),
        migrations.CreateModel(
            name='RegimenPensionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regimen_pensionario', models.CharField(max_length=45, verbose_name='Nombre de Régimen Pensionario')),
            ],
            options={
                'verbose_name': 'Régimen Pensionario',
                'verbose_name_plural': 'Regímenes Pensionarios',
                'db_table': 'regimen_pensionario',
                'ordering': ['nombre_regimen_pensionario'],
            },
        ),
        migrations.CreateModel(
            name='TipoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_planilla', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Tipo de Planilla')),
            ],
            options={
                'verbose_name': 'Tipo de Planilla',
                'verbose_name_plural': 'Tipos de Planilla',
                'db_table': 'tipo_planilla',
                'ordering': ['nombre_tipo_planilla'],
            },
        ),
        migrations.CreateModel(
            name='TipoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_servidor', models.CharField(max_length=45, verbose_name='Nombre de Tipo de Servidor')),
            ],
            options={
                'verbose_name': 'Tipo de Servidor',
                'verbose_name_plural': 'Tipos de Servidores',
                'db_table': 'tipo_servidor',
                'ordering': ['nombre_tipo_servidor'],
            },
        ),
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ugel', models.CharField(max_length=100, verbose_name='Nombre de Ugel')),
                ('nombre_corto', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre Corto')),
            ],
            options={
                'verbose_name': 'UGEL',
                'verbose_name_plural': 'UGELs',
                'db_table': 'ugel',
                'ordering': ['nombre_ugel'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RemuneracionBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.beneficiario', verbose_name='Beneficiario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Remuneración del Beneficiario',
                'verbose_name_plural': 'Remuneraciones de los Beneficiarios',
                'db_table': 'remuneracion_beneficiario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Remuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_haberes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total de Haberes')),
                ('total_descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total de Descuentos')),
                ('essalud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ESSALUD')),
                ('emitio_boleta', models.SmallIntegerField(blank=True, null=True, verbose_name='Emisión de Boleta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.periodo', verbose_name='Período')),
                ('tipo_planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.tipoplanilla', verbose_name='Tipo de Planilla')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remuneraciones', to='employees.empleado', verbose_name='Trabajador')),
                ('ugel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.ugel', verbose_name='UGEL')),
            ],
            options={
                'verbose_name': 'Remuneración',
                'verbose_name_plural': 'Remuneraciones',
                'db_table': 'remuneracion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CET', 'Carnet de extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Número de Documento')),
                ('paterno', models.CharField(blank=True, max_length=45, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=45, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(blank=True, max_length=45, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('email', models.CharField(blank=True, max_length=45, verbose_name='Email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='employees.user')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['paterno', 'materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HaberEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_haber', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto de Haber')),
                ('periodo_inicial', models.CharField(blank=True, max_length=6, verbose_name='Periodo Inicial')),
                ('periodo_final', models.CharField(blank=True, max_length=6, verbose_name='Periodo Final')),
                ('correlativo', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Correlativo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('haber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.haber', verbose_name='Haber del Trabajador')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='haberes', to='employees.empleado', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Haber del Empleado',
                'verbose_name_plural': 'Haberes de los Empleados',
                'db_table': 'haberes_empleados',
                'ordering': ['haber', 'correlativo'],
            },
        ),
        migrations.CreateModel(
            name='FuentePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente_planilla', models.CharField(blank=True, max_length=45, verbose_name='Nombre de Fuente de Planilla')),
                ('tipo_planilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.tipoplanilla', verbose_name='Tipo de Planilla')),
            ],
            options={
                'verbose_name': 'Fuente de Planilla',
                'verbose_name_plural': 'Fuentes de Planilla',
                'db_table': 'fuente_planilla',
                'ordering': ['nombre_fuente_planilla'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='employees.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='regimen_laboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.regimenlaboral', verbose_name='Régimen Laboral'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='regimen_pensionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.regimenpensionario', verbose_name='Régimen Pensionario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.tiposervidor', verbose_name='Tipo de Servidor'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ugel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.ugel', verbose_name='UGEL'),
        ),
        migrations.CreateModel(
            name='DescuentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto de Descuento')),
                ('periodo_inicial', models.CharField(blank=True, max_length=6, verbose_name='Periodo Inicial')),
                ('periodo_final', models.CharField(blank=True, max_length=6, verbose_name='Periodo Final')),
                ('correlativo', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Correlativo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.descuento', verbose_name='Descuento del Trabajador')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='employees.empleado', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Descuento del Empleado',
                'verbose_name_plural': 'Descuentos de los Empleados',
                'db_table': 'descuentos_empleados',
                'ordering': ['descuento', 'correlativo'],
            },
        ),
        migrations.CreateModel(
            name='ComisionAFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pensión')),
                ('seguro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Seguro')),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Comisión')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total')),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.afp', verbose_name='AFP')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.periodo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Comisión AFP',
                'verbose_name_plural': 'Comisiones AFP',
                'db_table': 'comision_afp',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='employees.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.persona', verbose_name='Persona'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, max_length=150, verbose_name='Descripción')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditoria',
                'ordering': ['id'],
            },
        ),
    ]
